package com.ytdlpk.app.ui

import com.ytdlpk.app.model.AppLanguage

data class UiStrings(
    val standardMode: String,
    val quickMode: String,
    val formatsTab: String,
    val optionsTab: String,
    val globalTab: String,
    val nestedGlobalTab: String,
    val enterUrl: String,
    val analyzing: String,
    val analyze: String,
    val quickDownloadHint: String,
    val quickQuality: String,
    val quickPlaylistMode: String,
    val quickDownloadOnPaste: String,
    val notifyWhenInactive: String,
    val quickDownload: String,
    val loadingFormats: String,
    val analyzeForFormats: String,
    val videoAudio: String,
    val videoOnly: String,
    val audioOnly: String,
    val pairedAudio: String,
    val selectFormat: String,
    val saveLocation: String,
    val browse: String,
    val filenameTemplate: String,
    val extractAudio: String,
    val includeAutoSubs: String,
    val mergeOutputFormat: String,
    val toolVersions: String,
    val checking: String,
    val checkLatest: String,
    val updateYtdlp: String,
    val updateFfmpeg: String,
    val themeSystem: String,
    val language: String,
    val mediaPreview: String,
    val title: String,
    val channel: String,
    val duration: String,
    val playlist: String,
    val playlistAll: String,
    val singleOnly: String,
    val cancel: String,
    val download: String,
    val progress: String,
    val analyzingFromUrl: String,
    val preparingDownload: String,
    val noActiveProgress: String,
    val errorPrefix: String,
    val infoTitle: String,
    val ok: String,
    val downloadCompleteNotification: String,
    val downloadFailedNotification: String
)

fun uiStrings(language: AppLanguage): UiStrings {
    return when (language) {
        AppLanguage.JAPANESE -> UiStrings(
            standardMode = "通常ダウンロード",
            quickMode = "クイックダウンロード",
            formatsTab = "形式",
            optionsTab = "ダウンロードルール",
            globalTab = "設定",
            nestedGlobalTab = "Global",
            enterUrl = "動画URLを入力...",
            analyzing = "解析中...",
            analyze = "解析",
            quickDownloadHint = "保存先/字幕/音声抽出などはオプション設定を使用します",
            quickQuality = "画質プロファイル",
            quickPlaylistMode = "プレイリスト",
            quickDownloadOnPaste = "貼り付け時に即ダウンロード",
            notifyWhenInactive = "非アクティブ時に完了通知を表示",
            quickDownload = "クイックダウンロード",
            loadingFormats = "形式を読み込み中...",
            analyzeForFormats = "解析すると形式一覧が表示されます",
            videoAudio = "動画+音声",
            videoOnly = "動画のみ",
            audioOnly = "音声のみ",
            pairedAudio = "結合する音声",
            selectFormat = "形式を選択",
            saveLocation = "保存先",
            browse = "参照",
            filenameTemplate = "ファイル名テンプレート",
            extractAudio = "音声抽出 (-x)",
            includeAutoSubs = "自動字幕を含める",
            mergeOutputFormat = "マージ出力形式",
            toolVersions = "ツールのバージョン",
            checking = "確認中...",
            checkLatest = "最新確認",
            updateYtdlp = "yt-dlp 更新",
            updateFfmpeg = "ffmpeg 更新",
            themeSystem = "テーマをシステムに合わせる",
            language = "言語",
            mediaPreview = "メディアプレビュー",
            title = "タイトル",
            channel = "チャンネル",
            duration = "再生時間",
            playlist = "プレイリスト",
            playlistAll = "全体",
            singleOnly = "単体のみ",
            cancel = "キャンセル",
            download = "ダウンロード",
            progress = "進捗",
            analyzingFromUrl = "URLから動画情報を解析中",
            preparingDownload = "ダウンロード開始中",
            noActiveProgress = "進行中の処理なし",
            errorPrefix = "エラー",
            infoTitle = "情報",
            ok = "OK",
            downloadCompleteNotification = "ダウンロードが完了しました",
            downloadFailedNotification = "ダウンロードに失敗しました"
        )

        AppLanguage.KOREAN -> UiStrings(
            standardMode = "일반 다운로드",
            quickMode = "퀵 다운로드",
            formatsTab = "포맷",
            optionsTab = "다운로드 규칙",
            globalTab = "설정",
            nestedGlobalTab = "Global",
            enterUrl = "동영상 URL 입력...",
            analyzing = "분석 중...",
            analyze = "분석",
            quickDownloadHint = "저장 위치/자막/오디오 추출은 옵션 설정값을 그대로 사용합니다",
            quickQuality = "화질 프로필",
            quickPlaylistMode = "플레이리스트 모드",
            quickDownloadOnPaste = "붙여넣기 시 바로 다운로드",
            notifyWhenInactive = "창이 비활성화일 때 완료 알림 표시",
            quickDownload = "퀵 다운로드",
            loadingFormats = "포맷 불러오는 중...",
            analyzeForFormats = "분석하면 포맷 목록이 표시됩니다",
            videoAudio = "영상+오디오",
            videoOnly = "영상만",
            audioOnly = "오디오만",
            pairedAudio = "병합할 오디오",
            selectFormat = "포맷 선택",
            saveLocation = "저장 위치",
            browse = "찾아보기",
            filenameTemplate = "파일명 템플릿",
            extractAudio = "오디오 추출 (-x)",
            includeAutoSubs = "자동 생성 자막 포함",
            mergeOutputFormat = "병합 출력 포맷",
            toolVersions = "도구 버전",
            checking = "확인 중...",
            checkLatest = "최신 버전 확인",
            updateYtdlp = "yt-dlp 업데이트",
            updateFfmpeg = "ffmpeg 업데이트",
            themeSystem = "시스템 테마 따르기",
            language = "언어",
            mediaPreview = "미디어 미리보기",
            title = "제목",
            channel = "채널",
            duration = "길이",
            playlist = "플레이리스트",
            playlistAll = "전체",
            singleOnly = "단일만",
            cancel = "취소",
            download = "다운로드",
            progress = "진행 상태",
            analyzingFromUrl = "URL에서 영상 정보를 분석 중",
            preparingDownload = "다운로드 시작 중",
            noActiveProgress = "진행 중인 작업 없음",
            errorPrefix = "오류",
            infoTitle = "안내",
            ok = "확인",
            downloadCompleteNotification = "다운로드가 완료되었습니다",
            downloadFailedNotification = "다운로드에 실패했습니다"
        )

        AppLanguage.ENGLISH -> UiStrings(
            standardMode = "Standard",
            quickMode = "Quick Download",
            formatsTab = "Formats",
            optionsTab = "Download Rules",
            globalTab = "Settings",
            nestedGlobalTab = "Global",
            enterUrl = "Enter video URL...",
            analyzing = "Analyzing...",
            analyze = "Analyze",
            quickDownloadHint = "Save location/subtitles/audio extraction use current option settings",
            quickQuality = "Quality profile",
            quickPlaylistMode = "Playlist mode",
            quickDownloadOnPaste = "Download immediately on paste",
            notifyWhenInactive = "Show completion notification when inactive",
            quickDownload = "Quick Download",
            loadingFormats = "Loading formats...",
            analyzeForFormats = "Analyze to load format list",
            videoAudio = "Video+Audio",
            videoOnly = "Video only",
            audioOnly = "Audio only",
            pairedAudio = "Paired audio",
            selectFormat = "Select format",
            saveLocation = "Save location",
            browse = "Browse",
            filenameTemplate = "Filename template",
            extractAudio = "Extract audio (-x)",
            includeAutoSubs = "Include Auto-generated Subtitles",
            mergeOutputFormat = "Merge output format",
            toolVersions = "Tool Versions",
            checking = "Checking...",
            checkLatest = "Check Latest",
            updateYtdlp = "Update yt-dlp",
            updateFfmpeg = "Update ffmpeg",
            themeSystem = "Theme follows system",
            language = "Language",
            mediaPreview = "Media Preview",
            title = "Title",
            channel = "Channel",
            duration = "Duration",
            playlist = "Playlist",
            playlistAll = "Playlist all",
            singleOnly = "Single only",
            cancel = "Cancel",
            download = "Download",
            progress = "Progress",
            analyzingFromUrl = "Analyzing Video from URL",
            preparingDownload = "Starting download",
            noActiveProgress = "No active progress",
            errorPrefix = "Error",
            infoTitle = "Info",
            ok = "OK",
            downloadCompleteNotification = "Download completed",
            downloadFailedNotification = "Download failed"
        )
    }
}
